# -*- mode: ruby -*-
# vi: set ft=ruby ;

Vagrant.configure("2") do |config|
  config.vm.box = "utopic64"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/utopic/current/utopic-server-cloudimg-amd64-vagrant-disk1.box"
  config.vm.synced_folder "../code", "/home/vagrant/code"
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "puppet/manifests"
    puppet.manifest_file="haskell.pp"
  end
end

